Add remove task
emmanuelsteven/My-ToDo-List pull request #3
Opened 2023-04-07 11:54 UTC by emmanuelsteven

In this section, I was able to work on these functionalities ;
-Remove all hardcoded items from the tasks array.
-Create a new JavaScript file for the new functionality.
-Implement a function for adding a new task.
-Implement a function for deleting a task.
-Implement a function for editing task descriptions.

2023-04-07 13:51 UTC, AdnanOlarmmi requested changes
Hi @emmanuelsteven, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice design.
- Nice implementations.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 13:51 UTC, AdnanOlarmmi commented on src/script.js
![mobile](https://user-images.githubusercontent.com/41163571/230618678-8d4e7875-e5a2-441e-88c9-dda9d70eeed9.gif)

- More information at the bottom 👇  wherever appropriate, 🏃

2023-04-07 13:51 UTC, AdnanOlarmmi commented on src/addRemove.js
> +              <span class="material-symbols-outlined delete"> delete </span>
- [ ] Nice one with the design from the image above. It seems the last item is not deleting except for one of the items before it is deleted, kindly fix that bug 😁. as it is a requirement.

2023-04-07 13:51 UTC, AdnanOlarmmi commented on src/script.js
>  const taskList = document.querySelector('.task-container');
- [ ] Kindly note that the edited text doesn't persist in the `localstorage` after refresh 🙃 as it is a requirement.

2023-04-07 13:51 UTC, AdnanOlarmmi commented on src/addRemove.js
> +          task.completed = true;
- [ ] Kindly note that the `completed` value doesn't persist in the `localstorage` after refresh. 😃 as it is a requirement.

2023-04-08 16:54 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @emmanuelsteven 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 17:51 UTC, merged